// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: test_parser.proto

package test_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParserTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath   string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileFormat string `protobuf:"bytes,2,opt,name=file_format,json=fileFormat,proto3" json:"file_format,omitempty"`
}

func (x *ParserTestRequest) Reset() {
	*x = ParserTestRequest{}
	mi := &file_test_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserTestRequest) ProtoMessage() {}

func (x *ParserTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserTestRequest.ProtoReflect.Descriptor instead.
func (*ParserTestRequest) Descriptor() ([]byte, []int) {
	return file_test_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParserTestRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ParserTestRequest) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

type ParserTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath   string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileFormat string `protobuf:"bytes,2,opt,name=file_format,json=fileFormat,proto3" json:"file_format,omitempty"`
}

func (x *ParserTestResponse) Reset() {
	*x = ParserTestResponse{}
	mi := &file_test_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserTestResponse) ProtoMessage() {}

func (x *ParserTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserTestResponse.ProtoReflect.Descriptor instead.
func (*ParserTestResponse) Descriptor() ([]byte, []int) {
	return file_test_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParserTestResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ParserTestResponse) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

var File_test_parser_proto protoreflect.FileDescriptor

var file_test_parser_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x11, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x52, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x69, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x32, 0x48, 0x0a, 0x11, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_parser_proto_rawDescOnce sync.Once
	file_test_parser_proto_rawDescData = file_test_parser_proto_rawDesc
)

func file_test_parser_proto_rawDescGZIP() []byte {
	file_test_parser_proto_rawDescOnce.Do(func() {
		file_test_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_parser_proto_rawDescData)
	})
	return file_test_parser_proto_rawDescData
}

var file_test_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_parser_proto_goTypes = []any{
	(*ParserTestRequest)(nil),  // 0: ParserTestRequest
	(*ParserTestResponse)(nil), // 1: ParserTestResponse
}
var file_test_parser_proto_depIdxs = []int32{
	0, // 0: ParserTestService.Parser:input_type -> ParserTestRequest
	1, // 1: ParserTestService.Parser:output_type -> ParserTestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_parser_proto_init() }
func file_test_parser_proto_init() {
	if File_test_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_parser_proto_goTypes,
		DependencyIndexes: file_test_parser_proto_depIdxs,
		MessageInfos:      file_test_parser_proto_msgTypes,
	}.Build()
	File_test_parser_proto = out.File
	file_test_parser_proto_rawDesc = nil
	file_test_parser_proto_goTypes = nil
	file_test_parser_proto_depIdxs = nil
}
