// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: test_parser.proto

package test_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParserTestService_Parser_FullMethodName = "/ParserTestService/Parser"
)

// ParserTestServiceClient is the client API for ParserTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParserTestServiceClient interface {
	Parser(ctx context.Context, in *ParserTestRequest, opts ...grpc.CallOption) (*ParserTestResponse, error)
}

type parserTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParserTestServiceClient(cc grpc.ClientConnInterface) ParserTestServiceClient {
	return &parserTestServiceClient{cc}
}

func (c *parserTestServiceClient) Parser(ctx context.Context, in *ParserTestRequest, opts ...grpc.CallOption) (*ParserTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserTestResponse)
	err := c.cc.Invoke(ctx, ParserTestService_Parser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserTestServiceServer is the server API for ParserTestService service.
// All implementations must embed UnimplementedParserTestServiceServer
// for forward compatibility.
type ParserTestServiceServer interface {
	Parser(context.Context, *ParserTestRequest) (*ParserTestResponse, error)
	mustEmbedUnimplementedParserTestServiceServer()
}

// UnimplementedParserTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParserTestServiceServer struct{}

func (UnimplementedParserTestServiceServer) Parser(context.Context, *ParserTestRequest) (*ParserTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parser not implemented")
}
func (UnimplementedParserTestServiceServer) mustEmbedUnimplementedParserTestServiceServer() {}
func (UnimplementedParserTestServiceServer) testEmbeddedByValue()                           {}

// UnsafeParserTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserTestServiceServer will
// result in compilation errors.
type UnsafeParserTestServiceServer interface {
	mustEmbedUnimplementedParserTestServiceServer()
}

func RegisterParserTestServiceServer(s grpc.ServiceRegistrar, srv ParserTestServiceServer) {
	// If the following call pancis, it indicates UnimplementedParserTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParserTestService_ServiceDesc, srv)
}

func _ParserTestService_Parser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParserTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserTestServiceServer).Parser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserTestService_Parser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserTestServiceServer).Parser(ctx, req.(*ParserTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParserTestService_ServiceDesc is the grpc.ServiceDesc for ParserTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ParserTestService",
	HandlerType: (*ParserTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parser",
			Handler:    _ParserTestService_Parser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_parser.proto",
}
