// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: parser.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices []float32             `protobuf:"fixed32,1,rep,packed,name=Vertices,proto3" json:"Vertices,omitempty"`
	Indices  []uint32              `protobuf:"varint,2,rep,packed,name=Indices,proto3" json:"Indices,omitempty"`
	Normals  []float32             `protobuf:"fixed32,3,rep,packed,name=Normals,proto3" json:"Normals,omitempty"`
	UV       []float32             `protobuf:"fixed32,4,rep,packed,name=UV,proto3" json:"UV,omitempty"`
	Material []*MaterialAttributes `protobuf:"bytes,5,rep,name=Material,proto3" json:"Material,omitempty"`
}

func (x *MeshAttributes) Reset() {
	*x = MeshAttributes{}
	mi := &file_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshAttributes) ProtoMessage() {}

func (x *MeshAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshAttributes.ProtoReflect.Descriptor instead.
func (*MeshAttributes) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{0}
}

func (x *MeshAttributes) GetVertices() []float32 {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *MeshAttributes) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *MeshAttributes) GetNormals() []float32 {
	if x != nil {
		return x.Normals
	}
	return nil
}

func (x *MeshAttributes) GetUV() []float32 {
	if x != nil {
		return x.UV
	}
	return nil
}

func (x *MeshAttributes) GetMaterial() []*MaterialAttributes {
	if x != nil {
		return x.Material
	}
	return nil
}

type MaterialAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Color   []float32 `protobuf:"fixed32,2,rep,packed,name=Color,proto3" json:"Color,omitempty"`
	Texture string    `protobuf:"bytes,3,opt,name=Texture,proto3" json:"Texture,omitempty"`
	Opacity int32     `protobuf:"varint,4,opt,name=opacity,proto3" json:"opacity,omitempty"`
}

func (x *MaterialAttributes) Reset() {
	*x = MaterialAttributes{}
	mi := &file_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialAttributes) ProtoMessage() {}

func (x *MaterialAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialAttributes.ProtoReflect.Descriptor instead.
func (*MaterialAttributes) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{1}
}

func (x *MaterialAttributes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MaterialAttributes) GetColor() []float32 {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *MaterialAttributes) GetTexture() string {
	if x != nil {
		return x.Texture
	}
	return ""
}

func (x *MaterialAttributes) GetOpacity() int32 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

type ParserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *ParserRequest) Reset() {
	*x = ParserRequest{}
	mi := &file_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserRequest) ProtoMessage() {}

func (x *ParserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserRequest.ProtoReflect.Descriptor instead.
func (*ParserRequest) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ParserRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ParserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeshAttr *MeshAttributes `protobuf:"bytes,1,opt,name=MeshAttr,proto3" json:"MeshAttr,omitempty"`
}

func (x *ParserResponse) Reset() {
	*x = ParserResponse{}
	mi := &file_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserResponse) ProtoMessage() {}

func (x *ParserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserResponse.ProtoReflect.Descriptor instead.
func (*ParserResponse) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{3}
}

func (x *ParserResponse) GetMeshAttr() *MeshAttributes {
	if x != nil {
		return x.MeshAttr
	}
	return nil
}

var File_parser_proto protoreflect.FileDescriptor

var file_parser_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1,
	0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x68, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x07, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x55, 0x56, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52, 0x02, 0x55,
	0x56, 0x12, 0x2f, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x08, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x22, 0x72, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x22, 0x3d, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x68, 0x41, 0x74,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x08, 0x4d, 0x65, 0x73, 0x68, 0x41,
	0x74, 0x74, 0x72, 0x32, 0x41, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x3b, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_parser_proto_rawDescOnce sync.Once
	file_parser_proto_rawDescData = file_parser_proto_rawDesc
)

func file_parser_proto_rawDescGZIP() []byte {
	file_parser_proto_rawDescOnce.Do(func() {
		file_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_parser_proto_rawDescData)
	})
	return file_parser_proto_rawDescData
}

var file_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_parser_proto_goTypes = []any{
	(*MeshAttributes)(nil),     // 0: MeshAttributes
	(*MaterialAttributes)(nil), // 1: MaterialAttributes
	(*ParserRequest)(nil),      // 2: ParserRequest
	(*ParserResponse)(nil),     // 3: ParserResponse
}
var file_parser_proto_depIdxs = []int32{
	1, // 0: MeshAttributes.Material:type_name -> MaterialAttributes
	0, // 1: ParserResponse.MeshAttr:type_name -> MeshAttributes
	2, // 2: ParserService.ParserModel:input_type -> ParserRequest
	3, // 3: ParserService.ParserModel:output_type -> ParserResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parser_proto_init() }
func file_parser_proto_init() {
	if File_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parser_proto_goTypes,
		DependencyIndexes: file_parser_proto_depIdxs,
		MessageInfos:      file_parser_proto_msgTypes,
	}.Build()
	File_parser_proto = out.File
	file_parser_proto_rawDesc = nil
	file_parser_proto_goTypes = nil
	file_parser_proto_depIdxs = nil
}
